USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE TELECOM_DB;
USE DATABASE TELECOM_DB;

CREATE OR REPLACE SCHEMA MAIN;
USE SCHEMA MAIN;

CREATE OR REPLACE STAGE CDR_STAGE
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('')
);

CREATE OR REPLACE STAGE CUSTOMER_STAGE
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('')
);

CREATE OR REPLACE STAGE TOWER_STAGE
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('')
);

CREATE OR REPLACE TABLE CDR_RAW(
    CALLID STRING,
    CALLER_NO STRING,
    RECEIVER STRING,
    DURATION STRING,
    CALLTYPE STRING,
    TOWERID STRING,
    TIME_STAMP STRING
);

CREATE OR REPLACE TABLE CUSTOMER_MASTER(
    PHONENUMBER STRING,
    CUSTOMERNAME STRING,
    PLANTYPE STRING
);

CREATE OR REPLACE TABLE TOWER_MASTER(
    TOWERID STRING,
    REGION STRING,
    CITY STRING
);

COPY INTO CDR_RAW
FROM @CDR_STAGE/CDR_RAW_Telecom.csv
ON_ERROR = 'CONTINUE';

COPY INTO CUSTOMER_MASTER
FROM @CUSTOMER_STAGE/CUSTOMER_MASTER_Telecom.csv
ON_ERROR = 'CONTINUE';

COPY INTO TOWER_MASTER
FROM @TOWER_STAGE/TOWER_MASTER_Telecom.csv
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE CDR_VALID(
    CALLID STRING,
    CALLER_NO STRING,
    RECEIVER STRING,
    DURATION NUMBER,
    CALLTYPE STRING,
    TOWERID STRING,
    CALL_TIME TIMESTAMP,
    REVENUE FLOAT,
    ISINTERNATIONAL INT
);


INSERT INTO CDR_VALID
SELECT 
    C.CALLID,
    C.CALLER_NO,
    C.RECEIVER,
    COALESCE(TRY_TO_NUMBER(C.DURATION),0),
    C.CALLTYPE,
    C.TOWERID,
    TRY_TO_TIMESTAMP(C.TIME_STAMP),
    COALESCE(TRY_TO_NUMBER(C.DURATION),0)*0.02,
    CASE WHEN C.CALLTYPE='INT' THEN 1 ELSE 0 END
FROM CDR_RAW C
LEFT JOIN CUSTOMER_MASTER CM
    ON C.CALLER_NO = CM.PHONENUMBER
LEFT JOIN TOWER_MASTER TM
    ON C.TOWERID = TM.TOWERID
QUALIFY ROW_NUMBER() OVER 
(PARTITION BY C.CALLID ORDER BY TRY_TO_TIMESTAMP(C.TIME_STAMP) DESC)=1;

CREATE OR REPLACE STREAM CDR_STREAM 
ON TABLE CDR_VALID;

CREATE OR REPLACE TABLE FACT_CDR(
    ID INT AUTOINCREMENT,
    CALLID STRING,
    CALLER_NO STRING,
    RECEIVER STRING,
    DURATION NUMBER,
    REVENUE FLOAT,
    ISINTERNATIONAL INT,
    CALLDATE DATE
);

MERGE INTO FACT_CDR T
USING (
    SELECT 
        CALLID,
        CALLER_NO,
        RECEIVER,
        DURATION,
        REVENUE,
        ISINTERNATIONAL,
        CAST(CALL_TIME AS DATE) AS CALLDATE
    FROM CDR_VALID
) S
ON T.CALLID = S.CALLID

WHEN NOT MATCHED THEN
INSERT (
    CALLID,
    CALLER_NO,
    RECEIVER,
    DURATION,
    REVENUE,
    ISINTERNATIONAL,
    CALLDATE
)
VALUES (
    S.CALLID,
    S.CALLER_NO,
    S.RECEIVER,
    S.DURATION,
    S.REVENUE,
    S.ISINTERNATIONAL,
    S.CALLDATE
);

INSERT INTO CDR_VALID SELECT * FROM CDR_VALID;

CREATE OR REPLACE TASK TELECOM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '5 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CDR_STREAM')
AS

MERGE INTO FACT_CDR T
USING (
    SELECT 
        CALLID,
        CALLER_NO,
        RECEIVER,
        DURATION,
        REVENUE,
        ISINTERNATIONAL,
        CAST(CALL_TIME AS DATE) AS CALLDATE
    FROM CDR_STREAM
) S
ON T.CALLID = S.CALLID

WHEN NOT MATCHED THEN
INSERT (
    CALLID,
    CALLER_NO,
    RECEIVER,
    DURATION,
    REVENUE,
    ISINTERNATIONAL,
    CALLDATE
)
VALUES (
    S.CALLID,
    S.CALLER_NO,
    S.RECEIVER,
    S.DURATION,
    S.REVENUE,
    S.ISINTERNATIONAL,
    S.CALLDATE
);

ALTER TASK TELECOM_TASK RESUME;

EXECUTE TASK TELECOM_TASK;

SELECT * FROM FACT_CDR;

CREATE OR REPLACE VIEW VW_KPI_SUMMARY AS
SELECT 
    COUNT(*) AS TOTAL_CALLS,
    SUM(REVENUE) AS TOTAL_REVENUE,
    AVG(DURATION) AS AVG_CALL_DURATION,
    SUM(REVENUE) / COUNT(*) AS REVENUE_PER_CALL
FROM FACT_CDR;

CREATE OR REPLACE VIEW VW_TOP_CALLERS AS
SELECT 
    CALLER_NO,
    COUNT(*) AS TOTAL_CALLS,
    SUM(REVENUE) AS TOTAL_REVENUE
FROM FACT_CDR
GROUP BY CALLER_NO
ORDER BY TOTAL_CALLS DESC;

CREATE OR REPLACE VIEW VW_DAILY_REVENUE AS
SELECT 
    CALLDATE,
    SUM(REVENUE) AS TOTAL_REVENUE
FROM FACT_CDR
GROUP BY CALLDATE;

CREATE OR REPLACE VIEW VW_INT_CALLS AS
SELECT COUNT(*) AS INT_CALLS
FROM FACT_CDR
WHERE ISINTERNATIONAL = 1;

CREATE OR REPLACE VIEW VW_LOCAL_CALLS AS
SELECT COUNT(*) AS LOCAL_CALLS
FROM FACT_CDR
WHERE ISINTERNATIONAL = 0;

SELECT 
    CALLDATE,
    SUM(REVENUE) AS DAILY_REVENUE
FROM FACT_CDR
GROUP BY CALLDATE
ORDER BY CALLDATE;

SELECT 
    CASE 
        WHEN ISINTERNATIONAL = 1 THEN 'International'
        ELSE 'Local'
    END AS CALL_TYPE,
    COUNT(*) AS TOTAL_CALLS
FROM FACT_CDR
GROUP BY CALL_TYPE;

SELECT * FROM VW_DAILY_REVENUE;
SELECT * FROM VW_INT_CALLS;
SELECT * FROM VW_KPI_SUMMARY;
SELECT * FROM VW_LOCAL_CALLS;
SELECT * FROM VW_TOP_CALLERS;